name: mrktradexpvtltd
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  intl: ^0.16.1
  http: ^0.12.2
  get_it: ^4.0.4
  qr_flutter: ^3.2.0
  getflutter: ^1.1.3
  url_launcher: ^5.0.3
  flutter_html: ^1.0.0
  flutter_webrtc: ^0.3.2
  image_picker: ^0.6.7+7
  path_provider: ^1.6.14
  awesome_dialog: ^1.2.0
  number_to_words: ^0.0.3
  progress_dialog: ^1.2.4
  cupertino_icons: ^0.1.3
  firebase_messaging: ^7.0.0
  webview_flutter: ^0.3.22+1
  shared_preferences: ^0.5.10
  permission_handler: ^5.0.1+1
  flutter_inappwebview: ^4.0.0+4
  flutter_staggered_grid_view: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/iv_empty.png
    - images/ic_konnect.png
    - images/splash_back.png
    - images/splash_screen.jpg
    - images/home/ic_about.png
    - images/home/ic_store.png
    - images/home/ic_offers.png
    - images/home/ic_support.png
    - images/home/ic_address.png
    - images/home/ic_banking.png
    - images/home/ic_contact.png
    - images/home/ic_gallery.png
    - images/home/ic_registration.png