name: mrktradexpvtltd
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.10
  intl: ^0.16.1
  http: ^0.12.2
  share: ^0.6.5+2
  get_it: ^5.0.1
  rxdart: ^0.24.1
  qr_flutter: ^3.2.0
  getflutter: ^1.1.3
  device_info: ^0.4.2+8
  url_launcher: ^5.0.3
  flutter_html: ^1.0.2
  image_picker: ^0.6.7+11
  image_cropper: ^1.3.1
  path_provider: ^1.6.18
  awesome_dialog: ^1.2.1
  number_to_words: ^0.0.3
  progress_dialog: ^1.2.4
  cupertino_icons: ^1.0.0
  firebase_messaging: ^7.0.3
  shared_preferences: ^0.5.12
  permission_handler: ^5.0.1+1
  flutter_inappwebview: ^4.0.0+4
  youtube_player_flutter: ^7.0.0+7
  flutter_staggered_grid_view: ^0.3.2
  flutter_local_notifications: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/iv_empty.png
    - images/ic_konnect.png
    - images/splash_back.png
    - images/splash_screen.jpg
    - images/home/ic_about.png
    - images/home/ic_store.png
    - images/home/ic_offers.png
    - images/home/ic_support.png
    - images/home/ic_address.png
    - images/home/ic_banking.png
    - images/home/ic_contact.png
    - images/home/ic_gallery.png
    - images/home/ic_registration.png